from setuptools import setup, find_packages

setup(
    name="fziq",
    version="0.1.0",
    description="Decentralized Experiential Training for Physical AI",
    author="Keke Abai",
    author_email="kabai@bu.edu",
    url="https://github.com/k-abai/FzIQ",
    license="MIT",
    packages=find_packages(),
    python_requires=">=3.10",
    install_requires=[
        "torch>=2.7.0",
        "transformers>=4.40.0",
        "peft>=0.10.0",
        "accelerate>=0.29.0",
        "datasets>=2.19.0",
        "trl>=0.8.6",
        "sentence-transformers>=2.7.0",
        "flask>=3.0.3",
        "flask-sqlalchemy>=3.1.1",
        "web3>=6.18.0",
        "numpy>=1.26.4",
        "scipy>=1.13.0",
        "matplotlib>=3.8.4",
        "pandas>=2.2.2",
        "scikit-learn>=1.4.2",
        "pyyaml>=6.0.1",
        "python-dotenv>=1.0.1",
        "tqdm>=4.66.2",
        "wandb>=0.16.6",
    ],
    classifiers=[
        "Development Status :: 3 - Alpha",
        "Intended Audience :: Science/Research",
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 3.10",
        "Topic :: Scientific/Engineering :: Artificial Intelligence",
    ],
)
